eureka:
  client:
    serviceUrl:
      defaultZone: http://172.21.0.2:8761/eureka/
server:
  port: 80
spring:
  application:
    name: gateway
zuul:
  host:
    connectTimeoutMillis: 5000
    socketTimeoutMillis: 5000
  routes:
    manage:
      path: /manage/**
      url: http://172.21.0.2
#      serviceId: manage