eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 80
spring:
  application:
    name: gateway
zuul:
  host:
    connectTimeoutMillis: 5000
    socketTimeoutMillis: 5000
  routes:
    manage:
      path: /api/**
      serviceId: api
